name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: py_3b_ej3b1_test
      id: py_3b_ej3b1_test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: py_3b_ej3b1_test
        setup-command: sudo -H pip install -r requirements.txt
        command: pytest 3b/ej3b1_test.py
        timeout: 10
        max-score: 1
    - name: py_3b_ej3b2_test
      id: py_3b_ej3b2_test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: py_3b_ej3b2_test
        setup-command: sudo -H pip install -r requirements.txt
        command: pytest 3b/ej3b2_test
        timeout: 10
        max-score: 1
    - name: py_3b_ej3b3_test
      id: py_3b_ej3b3_test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: py_3b_ej3b3_test
        setup-command: sudo -H pip install -r requirements.txt
        command: pytest 3b/ej3b3_test.py
        timeout: 10
        max-score: 1
    - name: py_3c_ej3c1_test
      id: py_3c_ej3c1_test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: py_3c_ej3c1_test
        setup-command: sudo -H pip install -r requirements.txt
        command: pytest 3c/ej3c1_test.py
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PY_3B_EJ3B1_TEST_RESULTS: "${{steps.py_3b_ej3b1_test.outputs.result}}"
        PY_3B_EJ3B2_TEST_RESULTS: "${{steps.py_3b_ej3b2_test.outputs.result}}"
        PY_3B_EJ3B3_TEST_RESULTS: "${{steps.py_3b_ej3b3_test.outputs.result}}"
        PY_3C_EJ3C1_TEST_RESULTS: "${{steps.py_3c_ej3c1_test.outputs.result}}"
      with:
        runners: py_3b_ej3b1_test,py_3b_ej3b2_test,py_3b_ej3b3_test,py_3c_ej3c1_test
